name: Vue 3 CI/CD
on:
  pull_request_review:
    types: [submitted]
jobs:
  eslint-check:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install and Test
        run: |
          bun install
          bun run lint
        env:
          CI: true